### ISSUE TITLE
Enhancement tracking list

### ISSUE THREAD

**Issue by AngelOnFira** [CarletonComputerScienceSociety/friend-zoner#13]
These are some things that could be improved with the bot.

- [ ] Auto shuffle every x minutes
  - You can say that an event is happening for the next 60 minutes and it will shuffle for that long at an interval
- [ ] Can guarantee that there will be at least 1 moderator per room
- [ ] Some countdown that a shuffle will happen soon
- [ ] You can say "shuffle in 1 minute" and it will tell people how long until
- [ ] Shuffles would be better if tried not to put people in the same session as before
- [ ] There should be a storage that tracks certain things
  - Which roles in the server can use the command
  - Which roles in a server are moderators
  - Defaults to simple local database, can use an external data store
- [ ] There should be an interface to manage what the bot is doing
  - To stop the bot during an event
  - To extend or shorten the period
- [ ] Add more to the readme about how to set up a development environment

**Open questions:**

When shuffling, will people be pinged that it's going to happen? Or should they expect to look in a certain channel to find out? How does this work on an automatic shuffle timer vs a manual shuffle?
